# Generated by Django 2.1.7 on 2019-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=200)),
                ('cc', models.CharField(max_length=200)),
                ('bcc', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('sent_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
