# Generated by Django 2.1.7 on 2019-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='body',
            field=models.CharField(max_length=2000),
        ),
    ]
